Repository packethost/terraform-provider-packet, pull requests merged in 2018-09, with the labels that each got.

#70 [datasource] packet_operating_system -> data source
  CHANGELOG.md
  packet/config.go
  packet/datasource_packet_operating_system.go
  packet/datasource_packet_operating_system_test.go
  packet/provider.go
  vendor/github.com/packethost/packngo/README.md
  vendor/github.com/packethost/packngo/devices.go
  vendor/github.com/packethost/packngo/email.go
  vendor/github.com/packethost/packngo/events.go
  vendor/github.com/packethost/packngo/hardware_reservations.go
  vendor/github.com/packethost/packngo/ip.go
  vendor/github.com/packethost/packngo/notifications.go
  vendor/github.com/packethost/packngo/operatingsystems.go
  vendor/github.com/packethost/packngo/organizations.go
  vendor/github.com/packethost/packngo/packngo.go
  vendor/github.com/packethost/packngo/projects.go
  vendor/github.com/packethost/packngo/spotmarketrequest.go
  vendor/github.com/packethost/packngo/two_factor_auth.go
  vendor/github.com/packethost/packngo/user.go
  vendor/github.com/packethost/packngo/vpn.go
  vendor/vendor.json
  website/docs/d/operating_system.html.markdown
  website/packet.erb
Labels: size/XL

#71 Data source spot market price
  packet/datasource_spot_market_price.go
  packet/provider.go
  website/docs/d/spot_market_price.html.markdown
  website/packet.erb
Labels: size/M

#74 fix broken documentation references
  website/docs/r/device.html.markdown
  website/docs/r/ip_attachment.html.markdown
Labels: size/XS

#73 Added importer to device and project
  packet/resource_packet_device.go
  packet/resource_packet_device_test.go
  packet/resource_packet_project.go
  packet/resource_packet_project_test.go
  packet/resource_packet_volume.go
  packet/resource_packet_volume_test.go
  vendor/github.com/packethost/packngo/volumes.go
  vendor/vendor.json
Labels: size/M

#72 [New feature] Spot Market Request
  packet/provider.go
  packet/resource_packet_spot_market_request.go
  packet/resource_packet_spot_market_request_test.go
  website/docs/r/spot_market_request.html.markdown
  website/packet.erb
Labels: size/XL
