Repository packethost/terraform-provider-packet, pull requests merged in 2019-11, with the labels that each got.

#194 HTTP client hotfix: don't retry on HTTP 5xx
  packet/config.go
Labels: size/S

#196 Add mutex guard to VLAN detachment
  packet/resource_packet_port_vlan_attachment.go
Labels: size/XS

#197 fix acceptance tests for Layer 2 networking (ports and VLANS)
  packet/resource_packet_port_vlan_attachment_test.go
Labels: size/S

#198 [SWE-5713] Adding Deprecation Warnings to Packet Terraform
  CHANGELOG.md
  packet/provider.go
  packet/resource_packet_connect.go
  website/docs/r/connect.html.markdown
Labels: dependencies, documentation, size/XS

#201 removed packet_conect
  CHANGELOG.md
  packet/resource_packet_connect.go
  website/docs/r/connect.html.markdown
  website/packet.erb
Labels: documentation, size/M
