Repository packethost/terraform-provider-packet, pull requests merged in 2019-03, with the labels that each got.

#116 Fix unordered lists
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#115 Encourage project reuse, fix indentation to 2 spaces
  website/docs/d/operating_system.html.markdown
  website/docs/d/precreated_ip_block.html.markdown
  website/docs/index.html.markdown
  website/docs/r/bgp_session.html.markdown
  website/docs/r/device.html.markdown
  website/docs/r/ip_attachment.html.markdown
  website/docs/r/project_ssh_key.html.markdown
  website/docs/r/reserved_ip_block.html.markdown
  website/docs/r/spot_market_request.html.markdown
  website/docs/r/ssh_key.html.markdown
  website/docs/r/vlan.html.markdown
  website/docs/r/volume.html.markdown
  website/docs/r/volume_attachment.html.markdown
Labels: documentation, size/XL

#117 Bump packngo to support network type conversion
  go.mod
  go.sum
  vendor/github.com/packethost/packngo/packngo.go
  vendor/github.com/packethost/packngo/ports.go
  vendor/modules.txt
Labels: dependencies, size/L

#119 bump to packngo with trimmed API calls for network_type
  go.mod
  go.sum
Labels: size/XS

#120 bump to packngo with device network_type
  go.sum
  vendor/github.com/packethost/packngo/devices.go
  vendor/github.com/packethost/packngo/ports.go
  vendor/modules.txt
Labels: dependencies, size/M

#121 Fix doc links to aim to support.packet.com
  website/docs/r/device.html.markdown
  website/docs/r/ip_attachment.html.markdown
  website/docs/r/project.html.markdown
  website/docs/r/spot_market_request.html.markdown
  website/docs/r/vlan.html.markdown
Labels: documentation, size/XS

#123 bunmp packngo to backend transfer support
  go.mod
  go.sum
  vendor/github.com/packethost/packngo/devices.go
  vendor/github.com/packethost/packngo/projects.go
  vendor/modules.txt
Labels: dependencies, size/S

#122 Backend transfer
  packet/resource_packet_project.go
  packet/resource_packet_project_test.go
  website/docs/r/project.html.markdown
Labels: dependencies, documentation, size/M

#86 Layer 2 support: Device ports and VLAN attachment
  packet/provider.go
  packet/resource_packet_device.go
  packet/resource_packet_device_test.go
  packet/resource_packet_port_vlan_attachment.go
  packet/resource_packet_port_vlan_attachment_test.go
  website/docs/r/device.html.markdown
  website/docs/r/port_vlan_attachment.html.markdown
  website/docs/r/vlan.html.markdown
  website/packet.erb
Labels: dependencies, documentation, size/XL

#127 docs/provider: Sort resource list and include packet_ prefix for data sources in sidebar
  website/packet.erb
Labels: documentation, size/S

#126 packngo bump to have more attributes in hw reservation
  go.mod
  go.sum
  vendor/github.com/packethost/packngo/hardware_reservations.go
  vendor/modules.txt
Labels: dependencies, size/XS

#129 misspelling
  website/docs/r/ip_attachment.html.markdown
Labels: documentation, size/XS

#132 bump packngo to version supporting Connect
  go.mod
  go.sum
  vendor/github.com/packethost/packngo/connect.go
  vendor/github.com/packethost/packngo/packngo.go
  vendor/modules.txt
Labels: dependencies, size/L

#130 Add resource for Packet Connect
  packet/provider.go
  packet/resource_packet_connect.go
  website/docs/r/connect.html.markdown
  website/packet.erb
Labels: documentation, size/L
