Repository packethost/terraform-provider-packet, pull requests merged in 2019-12, with the labels that each got.

#202 Improve volume attachment doc
  website/docs/r/volume_attachment.html.markdown
Labels: documentation, size/S

#203 fix wait for device state
  packet/resource_packet_device.go
Labels: size/M

#207 Use the address family provided, rather than just ipv4
  packet/resource_packet_bgp_session.go
  packet/resource_packet_bgp_session_test.go
Labels: size/XS

#208 explain #176 in packet_device doc
  website/docs/r/device.html.markdown
Labels: documentation, size/XS

#210 check if HTTP 404 Not Found comes indeed from API
  packet/errors.go
Labels: size/XS

#212 Update go-retryablehttp
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/go.mod
  vendor/modules.txt
Labels: dependencies, size/M

#213 Add sweepers to clean residual resources from Acceptance tests
  packet/datasource_packet_device_test.go
  packet/datasource_packet_ip_block_ranges_test.go
  packet/datasource_packet_organization_test.go
  packet/datasource_packet_precreated_ip_block_test.go
  packet/datasource_packet_spot_market_request_test.go
  packet/datasource_packet_volume_test.go
  packet/resource_packet_bgp_session_test.go
  packet/resource_packet_device_test.go
  packet/resource_packet_ip_attachment_test.go
  packet/resource_packet_organization_test.go
  packet/resource_packet_port_vlan_attachment_test.go
  packet/resource_packet_project_ssh_key_test.go
  packet/resource_packet_project_test.go
  packet/resource_packet_spot_market_request.go
  packet/resource_packet_spot_market_request_test.go
  packet/resource_packet_ssh_key_test.go
  packet/resource_packet_volume_attachment_test.go
  packet/sweeper_test.go
Labels: size/L
