Repository packethost/terraform-provider-packet, pull requests merged in 2019-05, with the labels that each got.

#147 extend error message on device creation in nonexistent project
  packet/resource_packet_device.go
Labels: size/XS

#148 bump packngo to support IP address type specs when creating device
  go.mod
  go.sum
  vendor/github.com/packethost/packngo/devices.go
  vendor/modules.txt
Labels: dependencies, size/XS

#150 Add field for selecting IP Address types when creating device
  packet/resource_packet_device.go
  website/docs/r/device.html.markdown
Labels: documentation, size/S

#151 docs/device: Document ports attribute
  website/docs/r/device.html.markdown
Labels: documentation, size/S

#152 resource/packet_port_vlan_attachment: Avoid parallel assignment
  packet/provider.go
  packet/resource_packet_port_vlan_attachment.go
  packet/resource_packet_port_vlan_attachment_test.go
  vendor/github.com/hashicorp/terraform/helper/mutexkv/mutexkv.go
  vendor/modules.txt
Labels: bug, dependencies, size/M
