Repository packethost/terraform-provider-packet, pull requests merged in 2019-10, with the labels that each got.

#177 Remove incorrect statemets wrt project ssh keys
  website/docs/r/project_ssh_key.html.markdown
Labels: documentation, size/XS

#174 Add timeouts to packet_device, defaults to 10 min
  packet/resource_packet_device.go
Labels: size/XS

#169 Make user_data not ForceNew, add update test
  packet/resource_packet_device.go
  packet/resource_packet_device_test.go
Labels: size/S

#171 Add ip_block_ranges datasource, doc
  packet/datasource_packet_ip_block_ranges.go
  packet/datasource_packet_ip_block_ranges_test.go
  packet/provider.go
  website/docs/d/ip_block_ranges.html.markdown
  website/packet.erb
Labels: documentation, size/L

#178 Updated Facilities Line to List
  website/docs/index.html.markdown
Labels: documentation, size/XS

#181 Set wait_for_reservation_deprovision to nil if unspecified by user
  packet/resource_packet_device.go
Labels: size/XS

#161 Add project datasource
  packet/datasource_packet_project.go
  packet/datasource_packet_project_test.go
  packet/provider.go
  website/docs/d/project.html.markdown
  website/packet.erb
Labels: documentation, size/L

#159 Datasource for spot market request
  packet/datasource_packet_device.go
  packet/datasource_packet_device_test.go
  packet/datasource_packet_spot_market_request.go
  packet/datasource_packet_spot_market_request_test.go
  packet/provider.go
  website/docs/d/device.html.markdown
  website/docs/d/spot_market_request.html.markdown
  website/packet.erb
Labels: documentation, size/XL

#162 Add datasouce for packet_volume, acceptance test and doc
  packet/datasource_packet_volume.go
  packet/datasource_packet_volume_test.go
  packet/provider.go
  website/docs/d/volume.html.markdown
  website/packet.erb
Labels: documentation, size/XL

#184 Added missing error handling when waiting for spot instances to complete
  CHANGELOG.md
  packet/resource_packet_spot_market_request.go
Labels: size/XS

#187 Bump Go version to 1.13
  .travis.yml
  README.md
  go.mod
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#186 Add packngo with retryable http
  .go-version
  go.mod
  go.sum
  packet/config.go
  vendor/github.com/hashicorp/go-retryablehttp/.gitignore
  vendor/github.com/hashicorp/go-retryablehttp/.travis.yml
  vendor/github.com/hashicorp/go-retryablehttp/LICENSE
  vendor/github.com/hashicorp/go-retryablehttp/Makefile
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/go.mod
  vendor/github.com/hashicorp/go-retryablehttp/go.sum
  vendor/github.com/packethost/packngo/.drone.yml
  vendor/github.com/packethost/packngo/Makefile
  vendor/github.com/packethost/packngo/README.md
  vendor/github.com/packethost/packngo/connect.go
  vendor/github.com/packethost/packngo/devices.go
  vendor/github.com/packethost/packngo/go.mod
  vendor/github.com/packethost/packngo/go.sum
  vendor/github.com/packethost/packngo/ip.go
  vendor/github.com/packethost/packngo/packngo.go
  vendor/github.com/packethost/packngo/volumes.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#188 Vlan resource import
  packet/resource_packet_vlan.go
  packet/resource_packet_vlan_test.go
Labels: size/XS

#189 Enable packet_ssh_key resource import
  packet/resource_packet_ssh_key.go
  packet/resource_packet_ssh_key_test.go
Labels: size/XS

#190 Enable packet_organization resource import & acc test
  packet/resource_packet_organization.go
  packet/resource_packet_organization_test.go
Labels: size/XS

#191 change org name in org datasource test
  packet/datasource_packet_organization_test.go
  packet/resource_packet_organization_test.go
Labels: size/XS

#192 Bump packngo to include Owner link in SSH key resources
  go.mod
  go.sum
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/packethost/packngo/devices.go
  vendor/github.com/packethost/packngo/sshkeys.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#193 Add import of project SSH keys
  packet/resource_packet_project_ssh_key.go
  packet/resource_packet_ssh_key.go
  packet/resource_packet_ssh_key_test.go
  website/docs/r/project_ssh_key.html.markdown
  website/docs/r/ssh_key.html.markdown
Labels: documentation, size/M
