Repository packethost/terraform-provider-packet, pull requests merged in 2019-02, with the labels that each got.

#92 Hotfix of network attribute order for packet_device
  CHANGELOG.md
  packet/resource_packet_device.go
  packet/resource_packet_device_test.go
  website/docs/r/bgp_session.html.markdown
  website/docs/r/device.html.markdown
Labels: documentation, size/S

#95 bump packngo with dfw2 included
  CHANGELOG.md
  vendor/github.com/packethost/packngo/devices.go
  vendor/github.com/packethost/packngo/ports.go
  vendor/github.com/packethost/packngo/spotmarketrequest.go
  vendor/github.com/packethost/packngo/utils.go
  vendor/vendor.json
Labels: dependencies, size/S

#93 allow list of facilities for packet_device
  packet/resource_packet_device.go
  packet/resource_packet_device_test.go
  website/docs/r/device.html.markdown
Labels: documentation, size/M

#97 bump packngo to support Global floating IP addresses
  packet/resource_packet_reserved_ip_block.go
  vendor/github.com/packethost/packngo/devices.go
  vendor/github.com/packethost/packngo/ip.go
  vendor/vendor.json
Labels: dependencies, size/XS

#98 bump packngo to support Global flag for IP blocks
  vendor/github.com/packethost/packngo/ip.go
  vendor/vendor.json
Labels: dependencies, size/XS

#100 [doc] Use real plans in the doc
  packet/datasource_packet_precreated_ip_block_test.go
  packet/resource_packet_bgp_session_test.go
  packet/resource_packet_device_test.go
  packet/resource_packet_ip_attachment_test.go
  packet/resource_packet_spot_market_request_test.go
  packet/resource_packet_volume_attachment_test.go
  website/docs/d/operating_system.html.markdown
  website/docs/d/precreated_ip_block.html.markdown
  website/docs/d/spot_market_price.html.markdown
  website/docs/index.html.markdown
  website/docs/r/bgp_session.html.markdown
  website/docs/r/device.html.markdown
  website/docs/r/spot_market_request.html.markdown
  website/docs/r/ssh_key.html.markdown
  website/docs/r/volume_attachment.html.markdown
Labels: documentation, size/S

#104 create useful error string when none generated from packngo
  packet/errors.go
  packet/resource_packet_reserved_ip_block.go
Labels: size/XS

#106 [docs] how to use the dev plugin in TF
  README.md
Labels: size/XS

#105 clarify the payment_method_id in project.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#96 Project ssh keys
  packet/provider.go
  packet/resource_packet_device.go
  packet/resource_packet_project_ssh_key.go
  packet/resource_packet_project_ssh_key_test.go
  packet/resource_packet_ssh_key.go
  website/docs/r/device.html.markdown
  website/docs/r/project_ssh_key.html.markdown
  website/packet.erb
Labels: documentation, size/L

#99 Global floating IP block reservation
  packet/datasource_packet_precreated_ip_block.go
  packet/resource_packet_ip_attachment.go
  packet/resource_packet_reserved_ip_block.go
  packet/resource_packet_reserved_ip_block_test.go
  website/docs/d/precreated_ip_block.html.markdown
  website/docs/r/reserved_ip_block.html.markdown
Labels: documentation, size/XL

#111 Handle resources that have been removed outside of TF
  CHANGELOG.md
  packet/resource_packet_bgp_session.go
  packet/resource_packet_ip_attachment.go
  packet/resource_packet_project_ssh_key.go
  packet/resource_packet_reserved_ip_block.go
  packet/resource_packet_spot_market_request.go
  packet/resource_packet_vlan.go
  packet/resource_packet_volume_attachment.go
Labels: size/S

#112 Allow facilities which are not yet in packngo
  CHANGELOG.md
  packet/resource_packet_device.go
  packet/resource_packet_device_test.go
  packet/resource_packet_reserved_ip_block.go
Labels: size/S
