Repository packethost/terraform-provider-packet, pull requests merged in 2019-01, with the labels that each got.

#87 [AUTOMATED] Upgrade to Go 1.11
  .travis.yml
  README.md
  packet/datasource_packet_precreated_ip_block_test.go
  packet/provider.go
  packet/resource_packet_device.go
  packet/resource_packet_device_test.go
  packet/resource_packet_ip_attachment_test.go
  packet/resource_packet_organization.go
  packet/resource_packet_organization_test.go
  packet/resource_packet_project.go
  packet/resource_packet_project_test.go
  packet/resource_packet_reserved_ip_block_test.go
  packet/resource_packet_spot_market_request.go
  packet/resource_packet_ssh_key.go
  packet/resource_packet_volume.go
  packet/resource_packet_volume_attachment_test.go
  packet/resource_packet_volume_test.go
Labels: size/L

#85 New resource: packet_vlan
  packet/provider.go
  packet/resource_packet_vlan.go
  packet/resource_packet_vlan_test.go
  website/docs/r/vlan.html.markdown
  website/packet.erb
Labels: dependencies, documentation, size/L

#89 keep device networks in specific order
  packet/resource_packet_device.go
  packet/resource_packet_device_test.go
  website/docs/r/device.html.markdown
Labels: documentation, size/M

#88 BGP support: extend project by BGP Config, new resource for BGP session
  packet/provider.go
  packet/resource_packet_bgp_session.go
  packet/resource_packet_bgp_session_test.go
  packet/resource_packet_project.go
  packet/resource_packet_project_test.go
  website/docs/r/bgp_session.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/XL
