Repository packethost/terraform-provider-packet, pull requests merged in 2020-07, with the labels that each got.

#237 Make userdata in packet_device ForceNew
  packet/resource_packet_device.go
  packet/resource_packet_device_test.go
Labels: size/S

#239 fix conversion from nil during WaitForState loops
  packet/helpers_device.go
Labels: size/XS

#240 Add new resource for Device Network Mode
  packet/provider.go
  packet/resource_packet_device.go
  packet/resource_packet_device_network_type.go
  packet/resource_packet_device_test.go
  packet/resource_packet_port_vlan_attachment_test.go
  website/docs/r/device.html.markdown
  website/docs/r/device_network_type.markdown
  website/docs/r/port_vlan_attachment.html.markdown
  website/packet.erb
Labels: documentation, size/XL

#242 update 3.0.0 CHANGELOG for BREAKING CHANGES
  CHANGELOG.md
Labels: size/XS
